### ISSUE TITLE
can you add default image or error image propertie?

### ISSUE THREAD

**Issue by ugurozcan** [jesusbotella/ngx-lazy-load-images#11]

**Comment by jesusbotella** [comment]
Hello @ugurozcan!
What do you mean by adding an error image property?

You can add a default image by setting the `src` property in your `<img>` tag, as well as the `data-src`, as you normally would:

```<img src="assets/default-image.png" data-src="assets/lazy-loaded-image.png" />```

**Comment by jesusbotella** [comment]
I am going to close this issue as I asked for more info and it has been inactive for so long. Please feel free to reopen it if you think it is necessary.
