### ISSUE TITLE
Compatibility with Angular 2

### ISSUE THREAD

**Issue by vishuml** [jesusbotella/ngx-lazy-load-images#14]
Are you sure the directive is compatible with angular 2? Because there's no Renderer2 in angular core 2nd version

**Comment by jesusbotella** [comment]
Hello @vishuml!
Yes, it is compatible with Angular 2+. There is a Renderer2 class listed in [Angular.io Docs](https://angular.io/api/core/Renderer2), and it is the recommended one. In fact, Renderer class is now deprecated as you can see [here](https://angular.io/api/core/Renderer).
