### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by vivek1996** [jesusbotella/ngx-lazy-load-images#15]
Can this  lazy-load can be used to lazy load  the content as it approaches the viewport ( when the size of the content very large ) Like this
![image](https://user-images.githubusercontent.com/15796694/41204915-89eed444-6d08-11e8-8ac8-f99a8c74ff9d.png)

**Comment by jesusbotella** [comment]
I am not sure about what you consider content, you can only lazy load images with this plugin.
It uses the IntersectionObserver API included in the browser to observe when images are visible in the viewport to load it.

**Comment by vivek1996** [comment]
Thankyou...
