### ISSUE TITLE
Add custom header before load image from server

### ISSUE THREAD

**Issue by amakhaev** [jesusbotella/ngx-lazy-load-images#16]
Hello. I want to add `authorization` header before send request to server. Could you please clarify it is possible?

```
Angular version: 6.0;
ngx-lazy-load-images: 1.3.1
```

**Comment by jesusbotella** [comment]
Hello @amakhaev! Sorry for my late reply.

No, you can't set any authorization headers to the image request with this plugin. The only way I know to do it is fetching the image and setting it to the `<img>` tag via blob content, like this:

```js
fetch('your image URL', { headers: { "Authorization": "your authentication header" } })
  .then(response => response.blob())
  .then(blob => {
    let url = URL.createObjectURL(blob);
    document.getElementById('image').src = url;
  })
```

And there's no way of doing that with this module. I am sorry ;)

**Comment by amakhaev** [comment]
Got it, thanks
