### ISSUE TITLE
images don't cache

### ISSUE THREAD

**Issue by mapsgeek** [jesusbotella/ngx-lazy-load-images#17]
normal behavior would be that browser loads images once and then the request is cached and get loaded from the cache, with this module it doesn't happen, browser loads images always by making request to the server, for something like pagination if you move between pages it comes more obvious

**Comment by mapsgeek** [comment]
sorry it's not the module fault, i didn't expect the image to come with no-cache header, so sorry

**Comment by jesusbotella** [comment]
Hello @mapsgeek!

You came to the correct conclusion! This module doesn't provide a mechanism to cache images, it delegates that functionality to the browser built-in methods.

Thank you for using this module ;)
