### ISSUE TITLE
Do we have an option of providing offset, so that images will get downloaded before they are in viewport

### ISSUE THREAD

**Issue by SravanthiSnapfish** [jesusbotella/ngx-lazy-load-images#18]
offset value should be 'Number of px a image should be loaded before it is in view port'

**Comment by jesusbotella** [comment]
Hello @SravanthiSnapfish!

You can set your own Intersection Observer configuration in the directive. Check it out in [_Intersection Observer Configuration_](https://github.com/jesusbotella/ngx-lazy-load-images#2-use-the-lazy-load-images-directive). It has an example of `rootMargin` property, which is the one you need ;)
