### ISSUE TITLE
Microsoft edge not showing images

### ISSUE THREAD

**Issue by Agustin-flubit** [jesusbotella/ngx-lazy-load-images#2]
I have tested last version on all browsers and is not showing images on Microsoft Edge.

![screen shot 2017-11-03 at 15 59 06](https://user-images.githubusercontent.com/31616668/32383471-f713c17a-c0af-11e7-85d2-2711093ad023.png)

this is my component (Parent).

 ```
<div *ngFor="let product of products" [ngClass]="layout ? 'product-container-' + layout + '-layout' : 'product-container-grid-layout'" lazy-load-images>
  <product-card
    class="product-card-layout"
    [ngClass]="layout ? 'product-' + layout + '-layout' : ''"
    [context]="layout"
    [product]="product">
  </product-card>
</div>
```

On product card component(Children):

```
<figure class="product-image-container">
  <a class="product-image-link image-link"
    [routerLink]="['/shop', 'p', product.slugTitle, product.id]"
    [queryParams]="getProductReferral()"
    (click)="onClickProduct(product.id)">
    <img class="product-image" [attr.data-src]="product.primary_image_ref | image:200:200" />
  </a>
</figure>
```

**Comment by jesusbotella** [comment]
Did you test it on other browsers and it worked, right?
Let me test it on Microsoft Edge. Your code does not have any issues as far as I saw.

**Comment by jesusbotella** [comment]
@Agustin-flubit I have just tested the page where you have the module, and it works successfully!

Could you please give me more information so I can reproduce the issue you are having? Please read my previous message as well.

**Comment by Agustin-flubit** [comment]
@jesusbotella I have tested in the rest of the browsers and it only fails on Edge. 
Try this link:
https://flubit.com/shop/search?category=Video%20Games&ch=true

As far as I see there is not any console error. 
Thanks

**Comment by jesusbotella** [comment]
I have just tried the page you mentioned and I didn't see any issue :(

![screenhot](https://user-images.githubusercontent.com/4319728/32399432-285d8fcc-c0f6-11e7-9238-6c74ee85aaee.PNG)

Which version is the one you use in MS Edge? Which OS?

**Comment by Agustin-flubit** [comment]
@jesusbotella I'va been testing  this issues and in some of them are showing, some of them not (90% not showing).
This is my version:
<img width="235" alt="screen shot 2017-11-06 at 15 34 01" src="https://user-images.githubusercontent.com/31616668/32449071-88541c3e-c308-11e7-8752-ef6646ce9caa.png">

I was testing cache, but after clear the cache is still not working.

**Comment by jesusbotella** [comment]
@Agustin-flubit could you please try to set a min-height and min-width of 1px to all the image elements and see what happen? Just like this:
```
min-width: 1px;
min-height: 1px;
```

I saw that on StackOverflow and I think it could be related to this issue: https://stackoverflow.com/questions/46391083/intersectionobserver-on-ie-edge

**Comment by Agustin-flubit** [comment]
@jesusbotella You are right, this setting fix this issue.
Thank you for your help

**Comment by jesusbotella** [comment]
You can do another optimization in your code, you do not need to use the directive in every `.product-container-grid-layout` element. You only need to put it one time in your `<flub-product-list>` element.

Please test it and tell me how it goes!

**Comment by Agustin-flubit** [comment]
@jesusbotella Thank you for the advise, It works fine.

**Comment by jesusbotella** [comment]
😀
