### ISSUE TITLE
Library is not SSR friendly

### ISSUE THREAD

**Issue by davidstellini** [jesusbotella/ngx-lazy-load-images#24]
When running server side, this library does not load images. As a workaround, I'm writing a directive to load them anyway under a server side render, but it would be nice if it were supported. 

Instead of 
```
if (!this.isBrowser()) {
      return;
    }
```

We can load all the images instead.

**Comment by davidstellini** [comment]
For anyone having the issue were images are not being loaded on the server side version, use this:

```
import {AfterViewInit, Directive, ElementRef, Inject, PLATFORM_ID} from '@angular/core';
import {isPlatformServer} from '@angular/common';

@Directive({
  selector: '[afSsrNoLazyLoad]'
})
export class SsrNoLazyLoadDirective implements AfterViewInit {
  private lazyLoadElements = [];
  private element;

  constructor(private elRef: ElementRef,
              @Inject(PLATFORM_ID) private platformId: string) {
      this.element = elRef.nativeElement;
  }

  ngAfterViewInit() {
      this.getAllLazyLoadElements(this.element);
      if(isPlatformServer(this.platformId)){
          this.updateImageSource();
      }
  }

  getAllLazyLoadElements (currentElement: HTMLElement) {
      this.lazyLoadElements = Array.from(currentElement.querySelectorAll('img[data-src], [data-srcset], [data-background-src]'));
  }

  updateImageSource() {
      for(let el of this.lazyLoadElements){
          switch (el.tagName) {
              case 'DIV':
                  el.style.backgroundImage = "url(" + el.getAttribute('data-background-src') +")";
                  break;
              case 'IMG':
                  el.setAttribute('src',"" + el.getAttribute('data-src'));
                  break;

          }
      }
  }
}
```

Then wherever you have `lazy-load-images`, add this directive along side like such:
`<div lazy-load-images afSsrNoLazyLoad> ...`

**Comment by jesusbotella** [comment]
Hi @davidstellini! Thank you for your work, I appreciate people collaborating to improve the library. 

Yes, you're right, the library does nothing to load images when rendering in server side, which is such a bummer. I tried to follow a similar approach to the one in your directive and it failed because `querySelectorAll` method was not available when rendering the application from server. Is it available now?

**Comment by davidstellini** [comment]
Hmm, I tried it and it's deployed right now, images are loading server side with this. Maybe they were some changes. I'm using ng7 + universal.
