### ISSUE TITLE
Getting security error.

### ISSUE THREAD

**Issue by Rupeshiya** [jesusbotella/ngx-lazy-load-images#26]
Here is the error, How can I fix this
![ngx](https://user-images.githubusercontent.com/31209617/58800992-f2afd680-8626-11e9-88ec-77a247ca8c3c.png)

**Comment by jesusbotella** [comment]
Hey! That seems to be an error with the interpolated URL inside `src` parameter.

Anyway, I have just released a new version with Angular 11 support, please upgrade your `ngx-lazy-load-images` dependency in package.json to `^2.0.0`.

If you encounter any problems while using it, please open a new issue.
