### ISSUE TITLE
Until this repo is updated, try ng-lazyload-image instead...

### ISSUE THREAD

**Issue by uberspeck** [jesusbotella/ngx-lazy-load-images#28]
~~Since this repo is no longer being maintained~~ Until this repo is updated I recommend trying https://github.com/tjoskar/ng-lazyload-image.

**Comment by jesusbotella** [comment]
Hi @uberspeck!

Sorry about that. It is true that I have not had time lately to update this repository so that the module works with Angular 9. I’m gonna open a PR to update and publish the module.

**Comment by jesusbotella** [comment]
I have just released a new version with Angular 11 support, please upgrade your `ngx-lazy-load-images` dependency in package.json to `^2.0.0`.

If you encounter any problems while using it, please open a new issue.
