### ISSUE TITLE
It would be great to have a placeholder for larger images to add 'progression' to the image.

### ISSUE THREAD

**Issue by matt-filion** [jesusbotella/ngx-lazy-load-images#3]
Something similar to what is outlined here, https://jmperezperez.com/medium-image-progressive-loading-placeholder/. Where you specify a tiny blurred version of the image to appear in place of the image that is about to be loaded.

**Comment by jesusbotella** [comment]
Thank you for proposal @matt-filion!

I think it would be great to have it, but I also believe that it is out of the scope of this plugin. But you can implement it in your application with this plugin if you want!

Please let me know if I can do something to improve the experience using the plugin.
