### ISSUE TITLE
Not support in Angular 11

### ISSUE THREAD

**Issue by saumilcmarix** [jesusbotella/ngx-lazy-load-images#30]
Hello I am using this version in my demo application and I am trying to use it in Angular 11 but I am getting an error described below
Error: node_modules/ngx-lazy-load-images/src/ngx-lazy-load-images.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-lazy-load-images) which declares LazyLoadImagesModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also, consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by Mozart-Alkhateeb** [comment]
to make it work, you'll need to disable Ivy in tsconfig.app.json like below 

  "angularCompilerOptions": {
    "enableIvy": false
  }
I hope @jesusbotella publishes an update soon

**Comment by jesusbotella** [comment]
Thank you for your issue.
I have just released a new version with Angular 11 support, please upgrade your `ngx-lazy-load-images` dependency in package.json to `^2.0.0`.

If you encounter any problems while using it, please open a new issue.

**Comment by saumilcmarix** [comment]
@jesusbotella Thanks, I will check and let you know.
