### ISSUE TITLE
all http requests doesn't terminate when scrolling a large list?

### ISSUE THREAD

**Issue by alsosweet** [jesusbotella/ngx-lazy-load-images#5]

**Comment by jesusbotella** [comment]
Are all the image request launch properly?

If your browser requests all the images but the requests are not completed successfully, it has something to do with your server/image server, and it is not an issue of this plugin.

I can offer more help if you elaborate your question :)

**Comment by alsosweet** [comment]
Thanks for your reply, you are right ,it is not  an issue of this plugin.I use https://github.com/rintoj/angular2-virtual-scroll to create a list, each item contain a<img>, when I scroll the list up or down very quickly, the <img> src value change to the new in the viewport, but the disappeared item's http request doesn't terminate. I thought it will work fine to integrate with this plugin, but I am wrong.

**Comment by jesusbotella** [comment]
You might need to check the HTTP request itself and see the reason why it doesn't finish successfully. If it is a timeout issue, it will be an issue of your image server/image provider. If it doesn't, it will be something else. But I think you will have to see what happens there to figure out any solution.

If you don't want to request image elements when scrolling quickly, you will have to do it by yourself by using the [IntersectionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) as this plugin does. And then you will need to set some requirements to avoid launching the request like "if the element stays less than 500ms inside the viewport" or something like that, but you will have to do it by yourself.

I'm going to close this issue but feel free to reopen a new one if you have any issue using this plugin.
Thank you!
